In [1]:
import alphalens
import pandas as pd
import numpy as np
import tushare as ts
import pytz
from pytz import timezone

In [2]:
ts.set_token('f3e51596fc5879d70b0995a267569e203c5d7e888f6b0df1799f0cf0')
pro=ts.pro_api()

In [3]:
data=pd.read_csv('F:\\Courses\\HKUST_Semester_Spring\\MAFS5210\\project1\\alphalen_test\\Data_for_alphlen.csv'
                ,sep=',')
data['ts_code']=data['ts_code'].apply(lambda x:x[:6]).tolist()

In [4]:
data['trade_date']=pd.to_datetime(data.trade_date,format="%Y/%m/%d")

In [145]:
data.RSI

0         56.380209
1         48.284286
2         46.045099
3         50.416416
4         53.771858
5         49.336533
6         45.363613
7         54.440863
8         54.046781
9         60.598956
10        65.765353
11        69.000841
12        62.621424
13        60.000505
14        55.508154
15        59.358067
16        54.937855
17        68.725715
18        72.558666
19        60.140275
20        61.532583
21        63.861141
22        49.789559
23        55.084687
24        59.094150
25        47.640401
26        45.048548
27        47.915093
28        45.386333
29        55.619255
            ...
103056    43.718136
103057    39.661310
103058    47.587735
103059    49.460654
103060    47.070220
103061    51.450581
103062    64.673669
103063    75.964211
103064    78.908758
103065    75.899706
103066    75.576886
103067    60.237723
103068    65.349847
103069    65.135093
103070    61.482637
103071    51.806915
103072    41.593243
103073    42.698539
103074    41.370117
103075    39.764202
103076          NaN
103077          NaN
103078          NaN
103079          NaN
103080          NaN
103081          NaN
103082          NaN
103083          NaN
103084          NaN
103085          NaN
Name: RSI, Length: 103086, dtype: float64

In [140]:
factor=pd.Series(np.array(data['RSI']),index=[data['trade_date'],data['ts_code']])

In [146]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly created array will be in C order (row major) unless 'F' is
        specified, in which case it will be in Fortran order (column major).
        If object is an array the following holds.

        ===== ========= ===================================================
        order  no copy                     copy=True
        ===== ========= ===================================================
        'K'   unchanged F & C order preserved, otherwise most similar order
        'A'   unchanged F order if input is F and not C, otherwise C order
        'C'   C order   C order
        'F'   F order   F order
        ===== ========= ===================================================

        When ``copy=False`` and a copy is made for other reasons, the result is
        the same as if ``copy=True``, with some exceptions for `A`, see the
        Notes section. The default order is 'K'.
    subok : bool, optional
        If True, then sub-classes will be passed-through, otherwise
        the returned array will be forced to be a base-class array (default).
    ndmin : int, optional
        Specifies the minimum number of dimensions that the resulting
        array should have.  Ones will be pre-pended to the shape as
        needed to meet this requirement.

    Returns
    -------
    out : ndarray
        An array object satisfying the specified requirements.

    See Also
    --------
    empty_like : Return an empty array with shape and type of input.
    ones_like : Return an array of ones with shape and type of input.
    zeros_like : Return an array of zeros with shape and type of input.
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.


    Notes
    -----
    When order is 'A' and `object` is an array in neither 'C' nor 'F' order,
    and a copy is forced by a change in dtype, then the order of the result is
    not necessarily 'C' as expected. This is likely a bug.

    Examples
    --------
    >>> np.array([1, 2, 3])
    array([1, 2, 3])

    Upcasting:

    >>> np.array([1, 2, 3.0])
    array([ 1.,  2.,  3.])

    More than one dimension:

    >>> np.array([[1, 2], [3, 4]])
    array([[1, 2],
           [3, 4]])

    Minimum dimensions 2:

    >>> np.array([1, 2, 3], ndmin=2)
    array([[1, 2, 3]])

    Type provided:

    >>> np.array([1, 2, 3], dtype=complex)
    array([ 1.+0.j,  2.+0.j,  3.+0.j])

    Data-type consisting of more than one element:

    >>> x = np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])
    >>> x['a']
    array([1, 3])

    Creating an array from sub-classes:

    >>> np.array(np.mat('1 2; 3 4'))
    array([[1, 2],
           [3, 4]])

    >>> np.array(np.mat('1 2; 3 4'), subok=True)
    matrix([[1, 2],
            [3, 4]])

In [141]:
factor

trade_date  ts_code
2019-05-31  603939     56.380209
2019-05-30  603939     48.284286
2019-05-29  603939     46.045099
2019-05-28  603939     50.416416
2019-05-27  603939     53.771858
2019-05-24  603939     49.336533
2019-05-23  603939     45.363613
2019-05-22  603939     54.440863
2019-05-21  603939     54.046781
2019-05-20  603939     60.598956
2019-05-17  603939     65.765353
2019-05-16  603939     69.000841
2019-05-15  603939     62.621424
2019-05-14  603939     60.000505
2019-05-13  603939     55.508154
2019-05-10  603939     59.358067
2019-05-09  603939     54.937855
2019-05-08  603939     68.725715
2019-05-07  603939     72.558666
2019-05-06  603939     60.140275
2019-04-30  603939     61.532583
2019-04-29  603939     63.861141
2019-04-26  603939     49.789559
2019-04-25  603939     55.084687
2019-04-24  603939     59.094150
2019-04-23  603939     47.640401
2019-04-22  603939     45.048548
2019-04-19  603939     47.915093
2019-04-18  603939     45.386333
2019-04-17  603939     55.619255
                         ...
2014-02-26  002252     43.718136
2014-02-25  002252     39.661310
2014-02-24  002252     47.587735
2014-02-21  002252     49.460654
2014-02-20  002252     47.070220
2014-02-19  002252     51.450581
2014-02-18  002252     64.673669
2014-02-17  002252     75.964211
2014-02-14  002252     78.908758
2014-02-13  002252     75.899706
2014-02-12  002252     75.576886
2014-02-11  002252     60.237723
2014-02-10  002252     65.349847
2014-02-07  002252     65.135093
2014-01-30  002252     61.482637
2014-01-29  002252     51.806915
2014-01-28  002252     41.593243
2014-01-27  002252     42.698539
2014-01-24  002252     41.370117
2014-01-23  002252     39.764202
2014-01-22  002252           NaN
2014-01-21  002252           NaN
2014-01-20  002252           NaN
2014-01-17  002252           NaN
2014-01-16  002252           NaN
2014-01-15  002252           NaN
2014-01-14  002252           NaN
2014-01-13  002252           NaN
2014-01-10  002252           NaN
2014-01-02  002252           NaN
Length: 103086, dtype: float64

In [7]:
ts_code=data['ts_code'].drop_duplicates()

In [8]:
#df['key'].apply(lambda x:x[:4]).tolist()

In [9]:

price=pd.DataFrame(data.loc[data['ts_code']=='603939',
                            ['trade_date','close']])
price.columns=['trade_date','603939']
short=pd.DataFrame([])
for i in range(len(ts_code)-1):
    new_price=data.loc[data['ts_code']==ts_code.iloc[i+1],
                       ['trade_date','close']]
    
    print(len(new_price['trade_date']))
    if (len(new_price['trade_date'])>=927):
        new_price.columns=['trade_date',ts_code.iloc[i+1]]
        l=min(len(price['trade_date']),len(new_price['trade_date']))
        print(l)
        price=price.iloc[0:l]
        new_price=new_price.iloc[0:l]
        price=pd.merge(price,new_price,on='trade_date',
                       how='outer')
    else:
        code=pd.DataFrame([ts_code.iloc[i+1]])
        short=pd.concat([short,code])
        continue;

909
447
1319
927
1163
999
1254
1111
1184
1176
957
957
1198
1198
1309
1275
1305
1285
1198
1198
1270
1270
1305
1305
1284
1284
1314
1314
1295
1295
1249
1249
1198
1198
1301
1301
1269
1269
1304
1304
1228
1228
1165
1165
1247
1246
1256
1256
1185
1185
617
1305
1269
1209
1209
1075
1075
1317
1252
1150
1150
1229
1229
1187
1187
1303
1303
1258
1258
1244
1244
1305
1269
1316
1305
1264
1264
1268
1268
1301
1301
1131
1131
913
1318
1315
1242
1242
1305
1305
1208
1208
666
1309
1309
1184
1184
1282
1245
1181
1181
1314
1274
1294
1294
1296
1296
1061
1061
1216
1216
1298
1280
1309
1309
1229
1229
1297
1297
1305
1305
1253
1253
1102
1102
986
986
1294
1043
1313
1064
1289
1070
1211
1100
1319
1120
1318
1120
1314
1121
1256
1126
859
1159
1159
1232
1232
1317
1317
1206
1206
1319
1274
971
971
1218
1218
1301
1298
1184
1184
919

In [10]:
price.iloc[0:927]

,trade_date,603939,600993,600763,600750,600664,600645,600572,600557,600521,...,000650,300267,600488,002275,000788,002393,600614,000518,600479,600829
0,2019-05-31,62.62,17.26,80.66,16.36,4.12,17.91,6.39,14.47,13.90,...,8.71,4.82,4.33,13.40,6.70,24.32,2.69,3.38,9.87,7.09
1,2019-05-30,61.01,17.44,80.98,16.37,4.19,17.81,6.39,14.29,13.61,...,9.00,4.99,4.30,13.85,6.73,24.29,2.56,3.40,9.90,7.08
2,2019-05-29,60.61,17.70,78.68,16.54,4.21,18.10,7.10,14.29,13.90,...,9.20,5.02,4.34,13.71,6.83,24.44,2.44,3.44,9.74,7.22
3,2019-05-28,61.50,17.70,78.92,16.53,4.28,18.27,7.16,14.20,13.93,...,9.34,5.04,4.33,13.70,6.82,24.50,2.32,3.46,9.70,7.22
4,2019-05-27,62.15,18.02,76.44,16.69,4.23,18.39,7.15,14.25,13.91,...,9.51,5.08,4.34,13.67,6.82,24.66,2.44,3.51,9.77,7.18
5,2019-05-24,61.20,16.92,75.91,16.56,4.14,17.84,6.87,13.95,13.58,...,8.97,4.82,4.25,13.39,6.72,24.21,2.57,3.46,9.53,6.94
6,2019-05-23,60.40,17.34,76.80,16.36,4.20,17.79,7.00,14.09,13.63,...,9.26,4.94,4.28,13.33,6.88,24.30,2.70,3.49,9.48,7.01
7,2019-05-22,62.29,17.65,76.83,16.61,4.26,18.26,7.16,14.25,13.82,...,9.50,5.14,4.34,13.54,6.92,24.66,2.84,3.63,9.62,7.21
8,2019-05-21,62.20,17.75,76.76,16.60,4.38,18.30,7.29,15.00,13.71,...,9.74,5.30,4.40,13.68,7.08,24.75,2.99,3.68,9.75,7.25
9,2019-05-20,63.45,17.25,75.20,16.43,4.34,17.56,7.07,14.27,13.65,...,8.85,5.12,4.31,13.55,6.80,24.52,3.15,3.64,9.58,6.98
10,2019-05-17,64.35,18.11,77.02,16.52,4.27,18.13,7.27,14.60,13.95,...,9.67,5.15,4.34,13.48,6.91,24.36,3.32,3.91,9.78,7.04
11,2019-05-16,64.90,18.37,79.60,16.90,4.58,18.60,7.85,14.94,14.56,...,9.62,5.70,4.50,13.81,7.19,25.00,3.49,3.86,10.06,7.45
12,2019-05-15,62.78,17.91,80.02,16.63,4.61,18.55,7.80,14.84,14.61,...,9.53,5.64,4.41,13.79,7.07,24.62,3.67,3.73,10.00,7.44
13,2019-05-14,62.03,16.53,76.70,16.38,4.43,18.36,7.57,13.82,14.27,...,8.66,5.41,4.44,13.57,6.98,24.20,3.86,3.67,9.80,7.33
14,2019-05-13,60.83,16.41,78.52,16.52,4.50,18.54,7.62,13.59,14.59,...,9.04,5.57,4.45,13.86,7.10,24.48,4.06,3.79,10.01,7.35
15,2019-05-10,61.60,16.83,77.00,16.80,4.65,18.81,7.84,13.66,14.34,...,9.16,5.80,4.41,13.86,7.00,24.64,4.27,3.89,10.22,7.50
16,2019-05-09,60.39,16.49,75.02,16.49,4.54,18.34,7.60,13.22,13.80,...,8.73,5.54,4.30,13.55,6.72,24.03,4.49,3.83,9.93,7.30
17,2019-05-08,62.87,17.51,77.00,16.58,4.70,18.55,7.85,13.92,14.81,...,9.39,5.79,4.28,13.68,6.98,24.18,4.73,3.94,10.07,7.41
18,2019-05-07,63.45,18.10,79.70,16.82,4.64,18.42,7.79,13.06,15.13,...,9.10,5.87,4.28,13.57,6.85,24.29,4.98,3.58,10.16,7.39
19,2019-05-06,59.85,17.02,74.46,16.41,4.44,18.08,7.50,13.85,13.99,...,8.27,5.65,4.18,13.33,6.57,23.69,5.24,3.30,10.00,7.10
20,2019-04-30,60.05,17.30,77.28,17.78,4.77,20.00,8.15,13.30,14.97,...,8.98,6.28,4.58,14.12,7.24,25.76,5.52,3.55,10.88,7.55
21,2019-04-29,60.40,16.59,78.07,17.75,4.77,19.46,7.87,14.30,14.14,...,8.16,6.89,4.47,14.01,7.08,25.61,5.81,3.49,10.87,7.35
22,2019-04-26,57.52,15.97,73.00,17.71,5.30,20.51,8.73,13.70,13.99,...,8.81,7.65,4.57,14.29,7.22,26.05,NaN,3.80,10.99,7.91
23,2019-04-25,58.31,15.85,68.80,18.00,5.46,20.52,8.70,14.22,14.54,...,8.53,8.03,4.99,14.50,7.36,26.60,6.12,3.89,11.20,8.32
24,2019-04-24,58.87,16.60,67.50,18.30,5.84,21.29,9.19,14.56,14.97,...,8.56,7.89,5.39,15.01,7.87,27.49,6.62,4.14,11.55,8.87
25,2019-04-23,57.00,16.77,68.38,18.24,5.31,21.01,9.08,13.94,15.35,...,8.83,8.41,5.02,14.55,7.84,27.72,6.61,4.32,11.48,8.06
26,2019-04-22,56.65,16.76,69.03,18.57,5.61,21.28,9.07,14.29,15.32,...,8.84,7.98,5.19,14.82,8.07,28.40,6.89,4.24,11.17,8.21
27,2019-04-19,57.12,17.08,66.85,18.84,5.82,21.61,9.63,14.53,15.80,...,8.20,7.69,5.00,14.98,8.12,28.53,6.88,4.33,11.17,8.41
28,2019-04-18,56.74,17.20,66.70,18.66,5.86,21.39,9.75,14.59,15.90,...,7.99,7.23,5.01,14.89,8.14,28.28,6.93,4.31,11.17,8.48
29,2019-04-17,58.34,17.15,67.83,18.79,6.08,21.49,10.18,14.06,16.20,...,7.26,8.00,4.90,15.05,8.25,28.56,7.13,4.47,11.23,8.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897,2015-04-07,61.97,NaN,68.07,31.86,10.93,68.29,23.10,28.76,20.13,...,11.54,57.64,8.64,23.89,19.93,40.37,NaN,NaN,23.85,16.83
898,2015-04-03,56.34,NaN,68.39,31.96,10.37,69.97,23.02,28.73,20.02,...,11.19,53.60,8.01,23.29,19.18,39.91,NaN,NaN,23.85,16.40
899,2015-04-02,56.26,NaN,67.93,32.06,10.41,69.51,21.99,28.25,19.35,...,10.83,54.46,8.03,23.02,19.01,39.50,NaN,NaN,22.50,16.48
900,2015-04-01,54.72,NaN,69.16,30.97,10.49,68.10,21.36,27.87,19.04,...,10.76,53.96,7.91,22.92,18.48,38.70,NaN,NaN,21.23,16.36
901,2015-03-31,53.90,NaN,68.64,29.97,10.29,66.03,21.12,27.36,17.52,...,10.48,49.05,7.83,22.38,18.69,38.15,NaN,NaN,20.87,15.29
902,2015-03-30,54.55,NaN,68.58,30.10,10.41,65.92,21.16,27.32,17.39,...,10.49,47.17,8.02,22.40,18.68,39.46,NaN,NaN,20.96,15.20
903,2015-03-27,55.22,NaN,66.33,30.09,10.44,62.28,20.88,26.64,17.43,...,10.43,45.83,8.02,22.49,19.47,39.17,23.69,NaN,20.01,15.30
904,2015-03-26,50.20,NaN,65.12,29.97,10.08,59.47,20.28,26.47,17.37,...,10.32,46.30,7.63,22.54,18.79,39.02,21.88,NaN,19.31,14.89
905,2015-03-25,50.80,NaN,65.75,29.94,10.09,61.65,20.73,26.67,17.62,...,10.76,46.79,7.61,22.50,19.14,39.80,21.16,NaN,18.86,14.84
906,2015-03-24,49.18,NaN,61.97,30.19,9.92,59.50,21.15,26.55,17.67,...,10.95,46.49,7.42,21.70,18.54,39.04,19.24,NaN,19.06,14.99
907,2015-03-23,51.01,NaN,61.85,30.96,10.11,58.66,20.99,26.94,17.48,...,10.18,47.59,7.33,21.98,18.18,39.68,19.00,NaN,19.54,15.33
908,2015-03-20,48.05,NaN,59.90,29.47,10.00,60.21,20.12,26.33,16.28,...,9.91,47.10,7.32,21.22,18.12,38.20,19.03,NaN,18.17,14.41
909,2015-03-19,47.63,NaN,59.72,29.67,9.87,60.00,19.60,26.49,15.90,...,10.01,43.60,7.05,20.93,18.14,37.03,19.26,NaN,NaN,14.61
910,2015-03-18,46.51,NaN,61.00,29.83,10.02,61.28,19.88,26.60,15.66,...,10.15,43.39,6.70,21.21,18.28,37.12,18.86,NaN,18.60,14.94
911,2015-03-17,46.31,NaN,60.96,29.72,9.88,60.10,18.07,26.31,15.46,...,9.97,43.62,6.58,20.90,17.94,36.91,18.83,NaN,18.71,14.43
912,2015-03-16,47.15,NaN,61.98,29.78,9.59,59.89,18.15,26.31,15.47,...,9.91,42.22,6.51,21.00,17.75,36.85,18.95,NaN,19.08,14.42
913,2015-03-13,45.34,NaN,61.94,28.41,9.45,59.98,17.52,25.57,15.16,...,9.57,40.84,6.34,20.69,17.37,36.10,18.28,NaN,18.29,14.16
914,2015-03-12,44.85,NaN,62.14,28.17,9.39,59.33,17.27,25.13,15.06,...,9.54,40.81,6.29,20.32,17.20,36.36,18.11,NaN,18.02,14.39
915,2015-03-11,46.16,NaN,61.29,28.38,9.44,60.42,17.54,25.26,15.06,...,9.72,42.00,6.30,20.60,17.65,35.55,18.27,NaN,18.21,14.37
916,2015-03-10,49.29,NaN,60.40,28.59,9.79,61.04,17.90,25.63,15.28,...,9.72,42.50,6.41,20.73,18.40,35.00,18.10,NaN,18.56,15.41
917,2015-03-09,48.24,NaN,58.52,28.25,9.86,55.49,17.72,25.60,15.31,...,9.74,41.55,6.44,20.48,17.91,34.79,17.43,NaN,18.07,15.22
918,2015-03-06,50.09,NaN,58.61,28.10,10.04,53.58,17.56,25.05,15.24,...,9.64,40.65,6.27,20.00,17.85,34.37,16.65,6.29,16.77,15.73
919,2015-03-05,53.01,NaN,60.81,28.72,9.94,56.17,18.11,25.65,15.63,...,9.95,42.10,6.22,20.20,18.49,35.16,17.31,6.27,16.95,14.30
920,2015-03-04,48.19,NaN,63.01,28.80,9.93,56.95,18.08,25.31,15.85,...,9.91,41.93,6.24,19.89,18.69,34.80,17.36,6.46,16.66,13.00
921,2015-03-03,45.14,NaN,60.68,28.15,9.56,53.37,17.24,24.91,14.57,...,9.76,42.29,6.07,19.28,17.55,34.35,17.12,6.03,16.67,NaN
922,2015-03-02,41.04,NaN,61.10,29.23,9.99,52.45,17.14,24.61,14.28,...,10.10,40.50,6.12,19.34,17.25,34.50,17.16,5.85,16.43,NaN
923,2015-02-27,37.31,NaN,59.86,29.64,9.74,48.81,17.08,24.34,14.34,...,9.99,39.07,6.11,19.27,16.74,34.33,16.22,5.75,15.70,NaN
924,2015-02-26,33.92,NaN,59.67,29.45,9.68,47.92,16.88,24.39,14.41,...,10.06,39.06,6.08,19.38,16.86,34.30,16.38,5.78,15.97,NaN
925,2015-02-25,30.84,NaN,59.66,29.68,9.78,48.61,16.94,23.82,14.34,...,10.18,39.62,6.05,19.20,17.14,34.28,15.89,5.73,15.74,NaN
926,2015-02-17,28.04,NaN,60.36,26.98,9.12,49.46,17.08,24.05,14.21,...,10.01,39.69,6.00,19.05,16.73,33.80,NaN,5.79,15.51,NaN

In [11]:
list(np.array(short.T)[0])

['603883', '603233', '002821', '000766', '603658', '002219', '002252']

In [12]:
a=list(price.columns)
b=list(np.array(short.T)[0])
ret = []
for i in a:
    if i not in b:
        ret.append(i)
price_f=price[ret].iloc[0:927]

In [13]:
price_f

,trade_date,603939,600993,600763,600750,600664,600645,600572,600557,600521,...,000650,300267,600488,002275,000788,002393,600614,000518,600479,600829
0,2019-05-31,62.62,17.26,80.66,16.36,4.12,17.91,6.39,14.47,13.90,...,8.71,4.82,4.33,13.40,6.70,24.32,2.69,3.38,9.87,7.09
1,2019-05-30,61.01,17.44,80.98,16.37,4.19,17.81,6.39,14.29,13.61,...,9.00,4.99,4.30,13.85,6.73,24.29,2.56,3.40,9.90,7.08
2,2019-05-29,60.61,17.70,78.68,16.54,4.21,18.10,7.10,14.29,13.90,...,9.20,5.02,4.34,13.71,6.83,24.44,2.44,3.44,9.74,7.22
3,2019-05-28,61.50,17.70,78.92,16.53,4.28,18.27,7.16,14.20,13.93,...,9.34,5.04,4.33,13.70,6.82,24.50,2.32,3.46,9.70,7.22
4,2019-05-27,62.15,18.02,76.44,16.69,4.23,18.39,7.15,14.25,13.91,...,9.51,5.08,4.34,13.67,6.82,24.66,2.44,3.51,9.77,7.18
5,2019-05-24,61.20,16.92,75.91,16.56,4.14,17.84,6.87,13.95,13.58,...,8.97,4.82,4.25,13.39,6.72,24.21,2.57,3.46,9.53,6.94
6,2019-05-23,60.40,17.34,76.80,16.36,4.20,17.79,7.00,14.09,13.63,...,9.26,4.94,4.28,13.33,6.88,24.30,2.70,3.49,9.48,7.01
7,2019-05-22,62.29,17.65,76.83,16.61,4.26,18.26,7.16,14.25,13.82,...,9.50,5.14,4.34,13.54,6.92,24.66,2.84,3.63,9.62,7.21
8,2019-05-21,62.20,17.75,76.76,16.60,4.38,18.30,7.29,15.00,13.71,...,9.74,5.30,4.40,13.68,7.08,24.75,2.99,3.68,9.75,7.25
9,2019-05-20,63.45,17.25,75.20,16.43,4.34,17.56,7.07,14.27,13.65,...,8.85,5.12,4.31,13.55,6.80,24.52,3.15,3.64,9.58,6.98
10,2019-05-17,64.35,18.11,77.02,16.52,4.27,18.13,7.27,14.60,13.95,...,9.67,5.15,4.34,13.48,6.91,24.36,3.32,3.91,9.78,7.04
11,2019-05-16,64.90,18.37,79.60,16.90,4.58,18.60,7.85,14.94,14.56,...,9.62,5.70,4.50,13.81,7.19,25.00,3.49,3.86,10.06,7.45
12,2019-05-15,62.78,17.91,80.02,16.63,4.61,18.55,7.80,14.84,14.61,...,9.53,5.64,4.41,13.79,7.07,24.62,3.67,3.73,10.00,7.44
13,2019-05-14,62.03,16.53,76.70,16.38,4.43,18.36,7.57,13.82,14.27,...,8.66,5.41,4.44,13.57,6.98,24.20,3.86,3.67,9.80,7.33
14,2019-05-13,60.83,16.41,78.52,16.52,4.50,18.54,7.62,13.59,14.59,...,9.04,5.57,4.45,13.86,7.10,24.48,4.06,3.79,10.01,7.35
15,2019-05-10,61.60,16.83,77.00,16.80,4.65,18.81,7.84,13.66,14.34,...,9.16,5.80,4.41,13.86,7.00,24.64,4.27,3.89,10.22,7.50
16,2019-05-09,60.39,16.49,75.02,16.49,4.54,18.34,7.60,13.22,13.80,...,8.73,5.54,4.30,13.55,6.72,24.03,4.49,3.83,9.93,7.30
17,2019-05-08,62.87,17.51,77.00,16.58,4.70,18.55,7.85,13.92,14.81,...,9.39,5.79,4.28,13.68,6.98,24.18,4.73,3.94,10.07,7.41
18,2019-05-07,63.45,18.10,79.70,16.82,4.64,18.42,7.79,13.06,15.13,...,9.10,5.87,4.28,13.57,6.85,24.29,4.98,3.58,10.16,7.39
19,2019-05-06,59.85,17.02,74.46,16.41,4.44,18.08,7.50,13.85,13.99,...,8.27,5.65,4.18,13.33,6.57,23.69,5.24,3.30,10.00,7.10
20,2019-04-30,60.05,17.30,77.28,17.78,4.77,20.00,8.15,13.30,14.97,...,8.98,6.28,4.58,14.12,7.24,25.76,5.52,3.55,10.88,7.55
21,2019-04-29,60.40,16.59,78.07,17.75,4.77,19.46,7.87,14.30,14.14,...,8.16,6.89,4.47,14.01,7.08,25.61,5.81,3.49,10.87,7.35
22,2019-04-26,57.52,15.97,73.00,17.71,5.30,20.51,8.73,13.70,13.99,...,8.81,7.65,4.57,14.29,7.22,26.05,NaN,3.80,10.99,7.91
23,2019-04-25,58.31,15.85,68.80,18.00,5.46,20.52,8.70,14.22,14.54,...,8.53,8.03,4.99,14.50,7.36,26.60,6.12,3.89,11.20,8.32
24,2019-04-24,58.87,16.60,67.50,18.30,5.84,21.29,9.19,14.56,14.97,...,8.56,7.89,5.39,15.01,7.87,27.49,6.62,4.14,11.55,8.87
25,2019-04-23,57.00,16.77,68.38,18.24,5.31,21.01,9.08,13.94,15.35,...,8.83,8.41,5.02,14.55,7.84,27.72,6.61,4.32,11.48,8.06
26,2019-04-22,56.65,16.76,69.03,18.57,5.61,21.28,9.07,14.29,15.32,...,8.84,7.98,5.19,14.82,8.07,28.40,6.89,4.24,11.17,8.21
27,2019-04-19,57.12,17.08,66.85,18.84,5.82,21.61,9.63,14.53,15.80,...,8.20,7.69,5.00,14.98,8.12,28.53,6.88,4.33,11.17,8.41
28,2019-04-18,56.74,17.20,66.70,18.66,5.86,21.39,9.75,14.59,15.90,...,7.99,7.23,5.01,14.89,8.14,28.28,6.93,4.31,11.17,8.48
29,2019-04-17,58.34,17.15,67.83,18.79,6.08,21.49,10.18,14.06,16.20,...,7.26,8.00,4.90,15.05,8.25,28.56,7.13,4.47,11.23,8.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897,2015-04-07,61.97,NaN,68.07,31.86,10.93,68.29,23.10,28.76,20.13,...,11.54,57.64,8.64,23.89,19.93,40.37,NaN,NaN,23.85,16.83
898,2015-04-03,56.34,NaN,68.39,31.96,10.37,69.97,23.02,28.73,20.02,...,11.19,53.60,8.01,23.29,19.18,39.91,NaN,NaN,23.85,16.40
899,2015-04-02,56.26,NaN,67.93,32.06,10.41,69.51,21.99,28.25,19.35,...,10.83,54.46,8.03,23.02,19.01,39.50,NaN,NaN,22.50,16.48
900,2015-04-01,54.72,NaN,69.16,30.97,10.49,68.10,21.36,27.87,19.04,...,10.76,53.96,7.91,22.92,18.48,38.70,NaN,NaN,21.23,16.36
901,2015-03-31,53.90,NaN,68.64,29.97,10.29,66.03,21.12,27.36,17.52,...,10.48,49.05,7.83,22.38,18.69,38.15,NaN,NaN,20.87,15.29
902,2015-03-30,54.55,NaN,68.58,30.10,10.41,65.92,21.16,27.32,17.39,...,10.49,47.17,8.02,22.40,18.68,39.46,NaN,NaN,20.96,15.20
903,2015-03-27,55.22,NaN,66.33,30.09,10.44,62.28,20.88,26.64,17.43,...,10.43,45.83,8.02,22.49,19.47,39.17,23.69,NaN,20.01,15.30
904,2015-03-26,50.20,NaN,65.12,29.97,10.08,59.47,20.28,26.47,17.37,...,10.32,46.30,7.63,22.54,18.79,39.02,21.88,NaN,19.31,14.89
905,2015-03-25,50.80,NaN,65.75,29.94,10.09,61.65,20.73,26.67,17.62,...,10.76,46.79,7.61,22.50,19.14,39.80,21.16,NaN,18.86,14.84
906,2015-03-24,49.18,NaN,61.97,30.19,9.92,59.50,21.15,26.55,17.67,...,10.95,46.49,7.42,21.70,18.54,39.04,19.24,NaN,19.06,14.99
907,2015-03-23,51.01,NaN,61.85,30.96,10.11,58.66,20.99,26.94,17.48,...,10.18,47.59,7.33,21.98,18.18,39.68,19.00,NaN,19.54,15.33
908,2015-03-20,48.05,NaN,59.90,29.47,10.00,60.21,20.12,26.33,16.28,...,9.91,47.10,7.32,21.22,18.12,38.20,19.03,NaN,18.17,14.41
909,2015-03-19,47.63,NaN,59.72,29.67,9.87,60.00,19.60,26.49,15.90,...,10.01,43.60,7.05,20.93,18.14,37.03,19.26,NaN,NaN,14.61
910,2015-03-18,46.51,NaN,61.00,29.83,10.02,61.28,19.88,26.60,15.66,...,10.15,43.39,6.70,21.21,18.28,37.12,18.86,NaN,18.60,14.94
911,2015-03-17,46.31,NaN,60.96,29.72,9.88,60.10,18.07,26.31,15.46,...,9.97,43.62,6.58,20.90,17.94,36.91,18.83,NaN,18.71,14.43
912,2015-03-16,47.15,NaN,61.98,29.78,9.59,59.89,18.15,26.31,15.47,...,9.91,42.22,6.51,21.00,17.75,36.85,18.95,NaN,19.08,14.42
913,2015-03-13,45.34,NaN,61.94,28.41,9.45,59.98,17.52,25.57,15.16,...,9.57,40.84,6.34,20.69,17.37,36.10,18.28,NaN,18.29,14.16
914,2015-03-12,44.85,NaN,62.14,28.17,9.39,59.33,17.27,25.13,15.06,...,9.54,40.81,6.29,20.32,17.20,36.36,18.11,NaN,18.02,14.39
915,2015-03-11,46.16,NaN,61.29,28.38,9.44,60.42,17.54,25.26,15.06,...,9.72,42.00,6.30,20.60,17.65,35.55,18.27,NaN,18.21,14.37
916,2015-03-10,49.29,NaN,60.40,28.59,9.79,61.04,17.90,25.63,15.28,...,9.72,42.50,6.41,20.73,18.40,35.00,18.10,NaN,18.56,15.41
917,2015-03-09,48.24,NaN,58.52,28.25,9.86,55.49,17.72,25.60,15.31,...,9.74,41.55,6.44,20.48,17.91,34.79,17.43,NaN,18.07,15.22
918,2015-03-06,50.09,NaN,58.61,28.10,10.04,53.58,17.56,25.05,15.24,...,9.64,40.65,6.27,20.00,17.85,34.37,16.65,6.29,16.77,15.73
919,2015-03-05,53.01,NaN,60.81,28.72,9.94,56.17,18.11,25.65,15.63,...,9.95,42.10,6.22,20.20,18.49,35.16,17.31,6.27,16.95,14.30
920,2015-03-04,48.19,NaN,63.01,28.80,9.93,56.95,18.08,25.31,15.85,...,9.91,41.93,6.24,19.89,18.69,34.80,17.36,6.46,16.66,13.00
921,2015-03-03,45.14,NaN,60.68,28.15,9.56,53.37,17.24,24.91,14.57,...,9.76,42.29,6.07,19.28,17.55,34.35,17.12,6.03,16.67,NaN
922,2015-03-02,41.04,NaN,61.10,29.23,9.99,52.45,17.14,24.61,14.28,...,10.10,40.50,6.12,19.34,17.25,34.50,17.16,5.85,16.43,NaN
923,2015-02-27,37.31,NaN,59.86,29.64,9.74,48.81,17.08,24.34,14.34,...,9.99,39.07,6.11,19.27,16.74,34.33,16.22,5.75,15.70,NaN
924,2015-02-26,33.92,NaN,59.67,29.45,9.68,47.92,16.88,24.39,14.41,...,10.06,39.06,6.08,19.38,16.86,34.30,16.38,5.78,15.97,NaN
925,2015-02-25,30.84,NaN,59.66,29.68,9.78,48.61,16.94,23.82,14.34,...,10.18,39.62,6.05,19.20,17.14,34.28,15.89,5.73,15.74,NaN
926,2015-02-17,28.04,NaN,60.36,26.98,9.12,49.46,17.08,24.05,14.21,...,10.01,39.69,6.00,19.05,16.73,33.80,NaN,5.79,15.51,NaN

In [14]:
price_f['trade_date']=pd.to_datetime(price_f.trade_date)
price_f.set_index('trade_date', drop = False, inplace = True)
Mt_Gambier= timezone('Australia/Adelaide')
price_f.index = price_f.index.tz_localize('UTC').tz_convert(Mt_Gambier)



price_f=price_f.set_index('trade_date')
price_f.columns.name='ts_code'

In [36]:
ds=ts.get_industry_classified()
ds

        code    name c_name
0     600051    宁波联合   综合行业
1     600209    罗顿发展   综合行业
2     600212    江泉实业   综合行业
3     600256    广汇能源   综合行业
4     600576    祥源文化   综合行业
5     600603    广汇物流   综合行业
6     600614    鹏起科技   综合行业
7     600620    天宸股份   综合行业
8     600622    光大嘉宝   综合行业
9     600624    复旦复华   综合行业
10    600647    同达创业   综合行业
11    600656    退市博元   综合行业
12    600687    刚泰控股   综合行业
13    600701    工大高新   综合行业
14    600730    中国高科   综合行业
15    600770    综艺股份   综合行业
16    600777    新潮能源   综合行业
17    600800    天津磁卡   综合行业
18    600805    悦达投资   综合行业
19    600811    东方集团   综合行业
20    600832    东方明珠   综合行业
21    600846    同济科技   综合行业
22    600892    大晟文化   综合行业
23    000008    神州高铁   综合行业
24    000301    东方市场   综合行业
25    000576    广东甘化   综合行业
26    000632    三木集团   综合行业
27    000633    合金投资   综合行业
28    000652    泰达股份   综合行业
29    000701    厦门信达   综合行业
...      ...     ...    ...
2878  600983     惠而浦   家电行业
2879  603366    日出东方   家电行业
2880  603519    立霸股份   家电行业
2881  000016    深康佳Ａ   家电行业
2882  000100  TCL 集团   家电行业
2883  000333    美的集团   家电行业
2884  000418    小天鹅Ａ   家电行业
2885  000521    美菱电器   家电行业
2886  000527    美的电器   家电行业
2887  000533   万 家 乐   家电行业
2888  000541    佛山照明   家电行业
2889  000651    格力电器   家电行业
2890  000921    海信科龙   家电行业
2891  002005    德豪润达   家电行业
2892  002032   苏 泊 尔   家电行业
2893  002035    华帝股份   家电行业
2894  002076   雪 莱 特   家电行业
2895  002242    九阳股份   家电行业
2896  002260    德奥通航   家电行业
2897  002290    中科新材   家电行业
2898  002403     爱仕达   家电行业
2899  002429    兆驰股份   家电行业
2900  002473   *ST圣莱   家电行业
2901  002508    老板电器   家电行业
2902  002543    万和电气   家电行业
2903  002668    奥马电器   家电行业
2904  002677    浙江美大   家电行业
2905  002681    奋达科技   家电行业
2906  002705    新宝股份   家电行业
2907  002723     金莱特   家电行业

[2908 rows x 3 columns]

In [43]:
ts_code.iloc[2]

'603233'

In [121]:
        new=pd.DataFrame({'code':['66666'],'c_name':['NaN']})

In [122]:
new

    code c_name
0  66666    NaN

In [126]:
group=pd.DataFrame([])
for i in range(len(ts_code)):
    new=ds.loc[ds.code==ts_code.iloc[i] ,['code','c_name']]
    group=pd.concat([group,new],axis=0)
for i in range(len(ts_code)):
    if ts_code.iloc[i] not in list(ds.code):
        new=pd.DataFrame({'code':[ts_code.iloc[i]],'c_name':['NaN']})
        group=pd.concat([group,new],axis=0)

In [127]:
group

        code c_name
875   603939   商业百货
874   603883   商业百货
339   600993   生物制药
963   600763   医疗器械
331   600750   生物制药
328   600664   生物制药
327   600645   生物制药
324   600572   生物制药
322   600557   生物制药
319   600521   生物制药
833   600511   商业百货
310   600380   生物制药
307   600329   生物制药
304   600267   生物制药
300   600216   生物制药
298   600201   生物制药
641   600195   农林牧渔
295   600161   生物制药
291   600079   生物制药
290   600062   生物制药
825   600056   商业百货
979   300244   医疗器械
431   300199   生物制药
419   300026   生物制药
2284  300253   电子信息
417   300009   生物制药
406   002603   生物制药
914   002589   商业百货
403   002437   生物制药
401   002424   生物制药
...      ...    ...
323   600566   生物制药
427   300147   生物制药
969   002551   医疗器械
400   002422   生物制药
373   002001   生物制药
425   300122   生物制药
412   002727   生物制药
343   603567   生物制药
930   600851   纺织行业
313   600436   生物制药
309   600351   生物制药
1674  002581   化工行业
368   000919   生物制药
335   600812   生物制药
408   002653   生物制药
359   000650   生物制药
385   002219   生物制药
437   300267   生物制药
316   600488   生物制药
388   002275   生物制药
364   000788   生物制药
397   002393   生物制药
6     600614   综合行业
351   000518   生物制药
315   600479   生物制药
336   600829   生物制药
386   002252   生物制药
0     603233    NaN
0     002821    NaN
0     603658    NaN

[86 rows x 2 columns]

In [79]:
group=group.set_index('code')

In [80]:
group.columns=['']

In [81]:
group.index.name=['']

In [82]:
group=group.iloc[:,0].to_dict()

In [84]:
group

{'000028': '商业百货',
 '000078': '生物制药',
 '000513': '生物制药',
 '000518': '生物制药',
 '000566': '生物制药',
 '000623': '生物制药',
 '000650': '生物制药',
 '000661': '生物制药',
 '000766': '生物制药',
 '000788': '生物制药',
 '000813': '纺织行业',
 '000919': '生物制药',
 '000999': '生物制药',
 '002001': '生物制药',
 '002019': '生物制药',
 '002022': '生物制药',
 '002030': '生物制药',
 '002038': '生物制药',
 '002118': '生物制药',
 '002219': '生物制药',
 '002223': '医疗器械',
 '002252': '生物制药',
 '002275': '生物制药',
 '002317': '生物制药',
 '002332': '生物制药',
 '002382': '医疗器械',
 '002390': '生物制药',
 '002393': '生物制药',
 '002399': '生物制药',
 '002422': '生物制药',
 '002424': '生物制药',
 '002437': '生物制药',
 '002551': '医疗器械',
 '002581': '化工行业',
 '002589': '商业百货',
 '002603': '生物制药',
 '002653': '生物制药',
 '002727': '生物制药',
 '300009': '生物制药',
 '300026': '生物制药',
 '300039': '生物制药',
 '300122': '生物制药',
 '300147': '生物制药',
 '300199': '生物制药',
 '300244': '医疗器械',
 '300253': '电子信息',
 '300267': '生物制药',
 '300273': '医疗器械',
 '300347': '医疗器械',
 '600056': '商业百货',
 '600062': '生物制药',
 '600079': '生物制药',
 '600161': '生物制药',
 '600195': '农林牧渔',
 '600201': '生物制药',
 '600216': '生物制药',
 '600267': '生物制药',
 '600329': '生物制药',
 '600351': '生物制药',
 '600380': '生物制药',
 '600422': '生物制药',
 '600436': '生物制药',
 '600479': '生物制药',
 '600488': '生物制药',
 '600511': '商业百货',
 '600521': '生物制药',
 '600557': '生物制药',
 '600566': '生物制药',
 '600572': '生物制药',
 '600587': '医疗器械',
 '600594': '生物制药',
 '600614': '综合行业',
 '600645': '生物制药',
 '600664': '生物制药',
 '600750': '生物制药',
 '600763': '医疗器械',
 '600812': '生物制药',
 '600829': '生物制药',
 '600851': '纺织行业',
 '600993': '生物制药',
 '603567': '生物制药',
 '603883': '商业百货',
 '603939': '商业百货'}

In [85]:
factor=factor.sort_index()

In [136]:
factor.

In [133]:
factor.to_csv('F:\\Courses\\HKUST_Semester_Spring\\MAFS5210\\project1\\factor.csv', 
                        sep=',', header=True, index=True)

In [99]:
price_f.head()

ts_code,603939,600993,600763,600750,600664,600645,600572,600557,600521,600511,...,000650,300267,600488,002275,000788,002393,600614,000518,600479,600829
trade_date,,,,,,,,,,,,,,,,,,,,,
2019-05-31,62.62,17.26,80.66,16.36,4.12,17.91,6.39,14.47,13.90,22.58,...,8.71,4.82,4.33,13.40,6.70,24.32,2.69,3.38,9.87,7.09
2019-05-30,61.01,17.44,80.98,16.37,4.19,17.81,6.39,14.29,13.61,22.75,...,9.00,4.99,4.30,13.85,6.73,24.29,2.56,3.40,9.90,7.08
2019-05-29,60.61,17.70,78.68,16.54,4.21,18.10,7.10,14.29,13.90,22.83,...,9.20,5.02,4.34,13.71,6.83,24.44,2.44,3.44,9.74,7.22
2019-05-28,61.50,17.70,78.92,16.53,4.28,18.27,7.16,14.20,13.93,22.82,...,9.34,5.04,4.33,13.70,6.82,24.50,2.32,3.46,9.70,7.22
2019-05-27,62.15,18.02,76.44,16.69,4.23,18.39,7.15,14.25,13.91,22.82,...,9.51,5.08,4.34,13.67,6.82,24.66,2.44,3.51,9.77,7.18

In [95]:
help(alphalens.utils.get_clean_factor_and_forward_returns)

Help on function get_clean_factor_and_forward_returns in module alphalens.utils:

get_clean_factor_and_forward_returns(factor, prices, groupby=None, binning_by_group=False, quantiles=5, bins=None, periods=(1, 5, 10), filter_zscore=20, groupby_labels=None, max_loss=0.35, zero_aware=False, cumulative_returns=True)
    Formats the factor data, pricing data, and group mappings into a DataFrame
    that contains aligned MultiIndex indices of timestamp and asset. The
    returned data will be formatted to be suitable for Alphalens functions.

    It is safe to skip a call to this function and still make use of Alphalens
    functionalities as long as the factor data conforms to the format returned
    from get_clean_factor_and_forward_returns and documented here

    Parameters
    ----------
    factor : pd.Series - MultiIndex
        A MultiIndex Series indexed by timestamp (level 0) and asset
        (level 1), containing the values for a single alpha factor.
        ::
            -----------------------------------
                date    |    asset   |
            -----------------------------------
                        |   AAPL     |   0.5
                        -----------------------
                        |   BA       |  -1.1
                        -----------------------
            2014-01-01  |   CMG      |   1.7
                        -----------------------
                        |   DAL      |  -0.1
                        -----------------------
                        |   LULU     |   2.7
                        -----------------------

    prices : pd.DataFrame
        A wide form Pandas DataFrame indexed by timestamp with assets
        in the columns.
        Pricing data must span the factor analysis time period plus an
        additional buffer window that is greater than the maximum number
        of expected periods in the forward returns calculations.
        It is important to pass the correct pricing data in depending on
        what time of period your signal was generated so to avoid lookahead
        bias, or  delayed calculations.
        'Prices' must contain at least an entry for each timestamp/asset
        combination in 'factor'. This entry should reflect the buy price
        for the assets and usually it is the next available price after the
        factor is computed but it can also be a later price if the factor is
        meant to be traded later (e.g. if the factor is computed at market
        open but traded 1 hour after market open the price information should
        be 1 hour after market open).
        'Prices' must also contain entries for timestamps following each
        timestamp/asset combination in 'factor', as many more timestamps
        as the maximum value in 'periods'. The asset price after 'period'
        timestamps will be considered the sell price for that asset when
        computing 'period' forward returns.
        ::
            ----------------------------------------------------
                        | AAPL |  BA  |  CMG  |  DAL  |  LULU  |
            ----------------------------------------------------
               Date     |      |      |       |       |        |
            ----------------------------------------------------
            2014-01-01  |605.12| 24.58|  11.72| 54.43 |  37.14 |
            ----------------------------------------------------
            2014-01-02  |604.35| 22.23|  12.21| 52.78 |  33.63 |
            ----------------------------------------------------
            2014-01-03  |607.94| 21.68|  14.36| 53.94 |  29.37 |
            ----------------------------------------------------

    groupby : pd.Series - MultiIndex or dict
        Either A MultiIndex Series indexed by date and asset,
        containing the period wise group codes for each asset, or
        a dict of asset to group mappings. If a dict is passed,
        it is assumed that group mappings are unchanged for the
        entire time period of the passed factor data.
    binning_by_group : bool
        If True, compute quantile buckets separately for each group.
        This is useful when the factor values range vary considerably
        across gorups so that it is wise to make the binning group relative.
        You should probably enable this if the factor is intended
        to be analyzed for a group neutral portfolio
    quantiles : int or sequence[float]
        Number of equal-sized quantile buckets to use in factor bucketing.
        Alternately sequence of quantiles, allowing non-equal-sized buckets
        e.g. [0, .10, .5, .90, 1.] or [.05, .5, .95]
        Only one of 'quantiles' or 'bins' can be not-None
    bins : int or sequence[float]
        Number of equal-width (valuewise) bins to use in factor bucketing.
        Alternately sequence of bin edges allowing for non-uniform bin width
        e.g. [-4, -2, -0.5, 0, 10]
        Chooses the buckets to be evenly spaced according to the values
        themselves. Useful when the factor contains discrete values.
        Only one of 'quantiles' or 'bins' can be not-None
    periods : sequence[int]
        periods to compute forward returns on.
    filter_zscore : int or float, optional
        Sets forward returns greater than X standard deviations
        from the the mean to nan. Set it to 'None' to avoid filtering.
        Caution: this outlier filtering incorporates lookahead bias.
    groupby_labels : dict
        A dictionary keyed by group code with values corresponding
        to the display name for each group.
    max_loss : float, optional
        Maximum percentage (0.00 to 1.00) of factor data dropping allowed,
        computed comparing the number of items in the input factor index and
        the number of items in the output DataFrame index.
        Factor data can be partially dropped due to being flawed itself
        (e.g. NaNs), not having provided enough price data to compute
        forward returns for all factor values, or because it is not possible
        to perform binning.
        Set max_loss=0 to avoid Exceptions suppression.
    zero_aware : bool, optional
        If True, compute quantile buckets separately for positive and negative
        signal values. This is useful if your signal is centered and zero is
        the separation between long and short signals, respectively.
    cumulative_returns : bool, optional
        If True, forward returns columns will contain cumulative returns.
        Setting this to False is useful if you want to analyze how predictive
        a factor is for a single forward day.

    Returns
    -------
    merged_data : pd.DataFrame - MultiIndex
        A MultiIndex Series indexed by date (level 0) and asset (level 1),
        containing the values for a single alpha factor, forward returns for
        each period, the factor quantile/bin that factor value belongs to, and
        (optionally) the group the asset belongs to.
        - forward returns column names follow  the format accepted by
          pd.Timedelta (e.g. '1D', '30m', '3h15m', '1D1h', etc)
        - 'date' index freq property (merged_data.index.levels[0].freq) will be
          set to a trading calendar (pandas DateOffset) inferred from the input
          data (see infer_trading_calendar for more details). This is currently
          used only in cumulative returns computation
        ::
           -------------------------------------------------------------------
                      |       | 1D  | 5D  | 10D  |factor|group|factor_quantile
           -------------------------------------------------------------------
               date   | asset |     |     |      |      |     |
           -------------------------------------------------------------------
                      | AAPL  | 0.09|-0.01|-0.079|  0.5 |  G1 |      3
                      --------------------------------------------------------
                      | BA    | 0.02| 0.06| 0.020| -1.1 |  G2 |      5
                      --------------------------------------------------------
           2014-01-01 | CMG   | 0.03| 0.09| 0.036|  1.7 |  G2 |      1
                      --------------------------------------------------------
                      | DAL   |-0.02|-0.06|-0.029| -0.1 |  G3 |      5
                      --------------------------------------------------------
                      | LULU  |-0.03| 0.05|-0.009|  2.7 |  G1 |      2
                      --------------------------------------------------------

In [128]:
# Ingest and format data
alphalens.utils.get_clean_factor_and_forward_returns(factor, price_f)

# Run analysis
alphalens.tears.create_full_tear_sheet(factor_data)

IndexError: index 927 is out of bounds for axis 0 with size 927